### ISSUE TITLE
Current Weather, Other EMWIN, Hurricane Center, and Local Settings not showing up

### ISSUE THREAD

**Issue by robert5603** [JVital2013/vitality-goes#88]
The server can display images in the full disk, non-CMIP, mesoscale, EMWIN, and NWS graphics sections. I also notice the system info section working just fine as well. However, I receive this error message when attempting to load the current weather section displaying alerts:
![Screenshot 2024-08-11 at 16-15-47 Current Weather - Vitality GOES](https://github.com/user-attachments/assets/6ba0c0ea-5239-4be1-804d-de6874a41233)

**Error message for Current Weather:**

<br />
<b>Fatal error</b>:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/home/pi/.pki): failed to open dir: Permission denied in /var/www/html/functions.php:241
Stack trace:
#0 [internal function]: RecursiveDirectoryIterator-&gt;__construct('/home/pi/.pki', 4128)
#1 /var/www/html/functions.php(241): RecursiveDirectoryIterator-&gt;getChildren()
#2 /var/www/html/dataHandler.php(1341): scandir_recursive('/home/pi', false)
#3 {main}
  thrown in <b>/var/www/html/functions.php</b> on line <b>241</b><br />

**Error message in Other EMWIN:**

<br />
<b>Fatal error</b>:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/home/pi/.pki): failed to open dir: Permission denied in /var/www/html/functions.php:241
Stack trace:
#0 [internal function]: RecursiveDirectoryIterator-&gt;__construct('/home/pi/.pki', 4128)
#1 /var/www/html/functions.php(241): RecursiveDirectoryIterator-&gt;getChildren()
#2 /var/www/html/dataHandler.php(287): scandir_recursive('/home/pi', false)
#3 {main}
  thrown in <b>/var/www/html/functions.php</b> on line <b>241</b><br />

**Error message in Hurricane Center:**

The server returned bad data:<br />
<b>Fatal error</b>:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/home/pi/.pki): failed to open dir: Permission denied in /var/www/html/functions.php:241
Stack trace:
#0 [internal function]: RecursiveDirectoryIterator-&gt;__construct('/home/pi/.pki', 4128)
#1 /var/www/html/functions.php(241): RecursiveDirectoryIterator-&gt;getChildren()
#2 /var/www/html/dataHandler.php(1097): scandir_recursive('/home/pi', false)
#3 {main}
  thrown in <b>/var/www/html/functions.php</b> on line <b>241</b><br />

**Error message in Local Settings:**

The server returned bad data: <br />
<b>Fatal error</b>:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/home/pi/.pki): failed to open dir: Permission denied in /var/www/html/functions.php:241
Stack trace:
#0 [internal function]: RecursiveDirectoryIterator-&gt;__construct('/home/pi/.pki', 4128)
#1 /var/www/html/functions.php(241): RecursiveDirectoryIterator-&gt;getChildren()
#2 /var/www/html/dataHandler.php(750): scandir_recursive('/home/pi', false)
#3 {main}
  thrown in <b>/var/www/html/functions.php</b> on line <b>241</b><br />

If there are additional files/resources you need, I am more than happy to send them your way.

**Comment by JVital2013** [comment]
This looks like a configuration error - it is trying to scan your entire /home/pi directory for EMWIN files, which is not what you want. Make sure `emwinPath` in your config.ini is set to the emwin folder directly.

**Comment by JVital2013** [comment]
I'm going to close this for now, but let me know if you have more issues!
